package io.factorialsystems.auth.model.enums;
public enum AuthEventType {
    LOGIN_SUCCESS, LOGIN_FAILURE, LOGOUT, TOKEN_REFRESH, PASSWORD_CHANGE, PASSWORD_RESET_REQUEST, PASSWORD_RESET_COMPLETE,
    ACCOUNT_LOCKED, ACCOUNT_UNLOCKED, ACCOUNT_ACTIVATED, ACCOUNT_DEACTIVATED, MFA_ENABLED, MFA_DISABLED,
    TENANT_CREATED, TENANT_ACTIVATED, TENANT_SUSPENDED, USER_CREATED, USER_UPDATED, USER_DELETED, ROLE_CREATED
}
