package io.factorialsystems.auth.model.enums;
public enum FacilityType { HOSPITAL, CLINIC, DIAGNOSTIC_CENTER, PHARMACY, MATERNITY, SPECIALIST_HOSPITAL, DENTAL_CLINIC, OPTICAL_CENTER, REHABILITATION_CENTER, NURSING_HOME, MENTAL_HEALTH_FACILITY, RESEARCH_INSTITUTE, BLOOD_BANK, OTHER }
